### ISSUE TITLE
[Rosetta Entities] Review

### ISSUE THREAD

**Issue by rllola** [Zondax/stacks-blockchain-api#13]
Stacks api also defined some entities used in multiple endpoint and also in TypeScript.

### Entities - Operation
`status` should not be required. At least not for construction endpoints.

### Entities - PublicKey
Missing curve types ? secp256r1 & tweedle (they are not used in this project but still valid values)

### Entities - NetworkIdentifier
In metadata, is `producer` required ?

**Comment by jleni** [comment]
Is this still pending?

**Comment by raynaudoe** [comment]
I've already reviewed the ones related to Data api.
If @rllola agrees we can close this one.

**Comment by rllola** [comment]
Let me check `Operation`

**Comment by rllola** [comment]
For `status` field in `operation`, the docs says :
```
On-chain operations (operations retrieved in the /block and /block/transaction endpoints) MUST have a populated status field (anything on-chain must have succeeded or failed). However, operations provided during transaction construction (often times called "intent" in the documentation) MUST NOT have a populated status field (operations yet to be included on-chain have not yet succeeded or failed).
```
https://www.rosetta-api.org/docs/models/Operation.html

So we have a bit of a conflict here. However I think it is ok if it is required by in the answer by contruction api and that it is populated with `intent`.

**Comment by rllola** [comment]
In the test they populated it with `success` but obviously the transaction is still being constructed so not successful.

https://github.com/blockstack/stacks-blockchain-api/blob/master/src/tests-rosetta/api.ts#L1420

**Comment by rllola** [comment]
As discussed with CB the `status` field in the construction API should only be `null` as the current status of the transaction is unknown at the time of the construction.

Closing this issue and opening a dedicated one for this.
