### ISSUE TITLE
Get testnet seed node url

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/stacks-blockchain-api#28]
for `mainnet` we have this url to check `stacks_tip_height`:
```typescript
  mainnet: {
    host: 'seed-2.mainnet.stacks.co',
    port: '20443',
  },
```
We need the same but for a `testnet` node.

**Comment by diwakergupta** [comment]
You can use `https://stacks-node-api.testnet.stacks.co/v2/info` or `http://testnet.stacks.co:20443/v2/info`

**Comment by raynaudoe** [comment]
Thanks!
