### ISSUE TITLE
Run rosetta-cli test

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/stacks-blockchain-api#29]
Run rosetta-cli test and post the results.

**Comment by jleni** [comment]
@raynaudoe It seems that we can already close this, could you confirm?

**Comment by raynaudoe** [comment]
We already have testnet results, mainnet is still pending due to rosetta-cli's "infinite loop" issue.

**Comment by raynaudoe** [comment]
rosetta-cli tests performed on mainnet achieved 99.99% of reconciliations coverage, without any errors.

```
start index: 2 (we start block 2 so we've already have all balances bootstrapped for minted accounts)
end index:  11075
```
Closing.
