### ISSUE TITLE
[Rosetta] Construction api is using by default testnet network in constructing payloads

### ISSUE THREAD

**Issue by rllola** [Zondax/stacks-blockchain-api#37]
I have missed this one 
https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/construction.ts#L467

Not sure if it matters in building the serialized transaction.

**Comment by rllola** [comment]
See https://github.com/Zondax/stacks-blockchain-api/pull/41

**Comment by raynaudoe** [comment]
We can close this one, right ?

**Comment by rllola** [comment]
Yes this is fixed

**Comment by rllola** [comment]
Not yet merged upstream tho. So reopening.

**Comment by rllola** [comment]
Merged upstream. Closing this.
