### ISSUE TITLE
`rewardRecipient` arg ignored in `getMinerRewards` function

### ISSUE THREAD

**Issue by zone117x** [Zondax/stacks-blockchain-api#55]
Just came across this:
https://github.com/Zondax/stacks-blockchain-api/blob/1cfb8df16b525dede70e9494c9926b55748971e5/src/datastore/postgres-store.ts#L1286-L1292

The query doesn't take into account the `rewardRecipient` arg.

**Comment by raynaudoe** [comment]
That arg is not needed actually, since that function returns all the rewards that all miners got at `blockHeight`.
I'll rename the function so it's more clear what's returning and also delete the `rewardRecipient` arg.
