### ISSUE TITLE
[Rosetta][Data-API][feature] stacking transactions

### ISSUE THREAD

**Issue by shermanxiong** [Zondax/stacks-blockchain-api#60]
The Data API needs to be able to show stacking transactions and the subsequent token lock/unlock operations so that Coinbase can finalize these transactions and update account balances in our internal databases

**Comment by shermanxiong** [comment]
https://github.com/blockstack/stacks-blockchain-api/pull/613

**Comment by raynaudoe** [comment]
Hi @shermanxiong, the `stx-lock` and `stx-unlock` transactions types were added on the PR you mentioned.

**Comment by jleni** [comment]
@raynaudoe Should we close this?

**Comment by raynaudoe** [comment]
Yes, it's already implemented
